apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: testsample.azurecr.io/chhajerkhushboo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  #namespace: tfo-dev
spec:
  #type: NodePort
  ports:
  - port: 80
  selector:
    app: sample